name: build_stunning_waddle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_on_os:
        description: 'Select OS to run'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - ubuntu-24.04
          - macos-15

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.run_on_os }}" != "both" ]]; then
            echo "matrix={\"os\":[\"${{ github.event.inputs.run_on_os }}\"]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"os\":[\"ubuntu-24.04\",\"macos-15\"]}" >> $GITHUB_OUTPUT
          fi

  build_and_test:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout_repository
        uses: actions/checkout@v4

      - name: install_linux_dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: install_dependencies_macos
        if: matrix.os == 'macos-15'
        run: |
          xcode-select -p

      - name: configure_cmake
        run: |
          cmake -S . -B build -DBUILD_TESTING=ON

      - name: build_project
        run: |
          cmake --build build

      - name: run_tests
        run: |
          cd build
          ctest -V
